# Generated by Django 3.1 on 2020-09-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_auto_20200916_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='reg_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
