# Generated by Django 3.1 on 2020-09-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_remove_students_reg_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scores',
            name='reg_date',
        ),
    ]
