# Generated by Django 3.1 on 2020-09-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_remove_scores_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='reg_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
