# Generated by Django 3.1 on 2020-09-16 03:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_scores_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='reg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
