# Generated by Django 3.1 on 2020-09-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_scores_reg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
