# Generated by Django 3.1 on 2020-09-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Pending', '할일'), ('Inprogress', '진행중'), ('End', '완료')], max_length=10),
        ),
    ]
